name:                miso-client-pt-zero-nineteen-ghc-stub
version:             0.1.0.0
github:              "githubuser/miso-client-pt-zero-nineteen-ghc-stub"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/miso-client-pt-zero-nineteen-ghc-stub#readme>

dependencies:
- base >= 4.7 && < 5
- async
- bytestring
- containers
- mtl
- stm
- text
- transformers
- unordered-containers
- vector
- filepath
- directory
- unix
- show-prettyprint
- wl-pprint-text
- path
- time
- binary
- deepseq
- aeson

- ghc-prim
- primitive

- template-haskell
- scientific
- integer-gmp
- attoparsec
- dlist >= 0.7  && < 0.9
- hashable >= 1.2  && < 1.3

- http-api-data
- http-types
- network-uri
- servant

library:
  source-dirs:
      - libs/prelude
      - src/miso-ghcjs-client
      - src/ghcjs-base
      - src/ghcjs-prim
      - src/miso-shared

executables:
  miso-client-pt-zero-nineteen-ghc-stub-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - miso-client-pt-zero-nineteen-ghc-stub

tests:
  miso-client-pt-zero-nineteen-ghc-stub-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - miso-client-pt-zero-nineteen-ghc-stub
